package tests

import ic.lex._
import ic.error._

/**
 * Sample Unit Tests for the IC lexer.
 *
 * You should be able to test much of your lexer's functionality
 * via unit tests, although you should also use full specification
 * tests on both good and bad files.
 *
 * Run these with `sbt test`.
 */
class LexicalTests extends munit.FunSuite {

  // demonstrates how to write a simple unit test
  test("Simple Succeeding Test") {
    val lexer = new Lexer("()")
    assertEquals(lexer.next().map(_.kind), Some(TokenKind.LPAREN))
  }

  // demonstrates how to say an exception should be generated by
  // a test.
  test("Expecting an exception to be raised") {
    val lexer = new Lexer("+")
    intercept[LexicalError] {
      lexer.next()
    }
  }
}
